### ISSUE TITLE
Pre-commit hook does not check linting for unity test files

### ISSUE THREAD

**Issue by lukasostendorf** [HAMNET-Access-Protocol/HNAP4PlutoSDR#35]
The current pre-commit hook configuration only runs the linter for files in the `src/` directory:

From `.pre-commit-config.yaml`:
```yaml
      hooks:
          - id: clang-format
            args: [-i]
            files: 'src/.*\.[ch]'
```

We also have to check for the unit test files within the `tests/` directory. Otherwise the local linting may succeed and the github linting action still fails. However, I do not know how to exclude the `tests/unity` folder within the `tests/` folder as it is done for the  github workflow.
